package modelos;
// Generated 21-mar-2015 8:56:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="taller1"
)
public class Persona  implements java.io.Serializable {


     private int personaId;
     private String nombre;
     private String apellidos;
     private String email;
     private Set tareas = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int personaId) {
        this.personaId = personaId;
    }
    public Persona(int personaId, String nombre, String apellidos, String email, Set tareas) {
       this.personaId = personaId;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.tareas = tareas;
    }
   
     @Id 

    
    @Column(name="persona_id", unique=true, nullable=false)
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", length=90)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


