package modelos;
// Generated 21-mar-2015 8:56:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="taller1"
)
public class Proyecto  implements java.io.Serializable {


     private int proyectoId;
     private String nombre;
     private String descripcion;
     private Set tareas = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(int proyectoId) {
        this.proyectoId = proyectoId;
    }
    public Proyecto(int proyectoId, String nombre, String descripcion, Set tareas) {
       this.proyectoId = proyectoId;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tareas = tareas;
    }
   
     @Id 

    
    @Column(name="proyecto_id", unique=true, nullable=false)
    public int getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(int proyectoId) {
        this.proyectoId = proyectoId;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


